### ISSUE TITLE
Add coin ethereum

### ISSUE THREAD

**Issue by vieyang** [MerosCrypto/asmr#3]
> That said, any Bitcoin-fork without SegWit, or any similar transaction malleability guarantees, will not work securely with this library (any by definition cannot implement this swap protocol atomically).

Can we add ethereum to auto swap with monero?

**Comment by kayabaNerve** [comment]
Ethereum is possible, for both Ether and ERC20s. It'd need to be partnered with a smart contract, preferably a singular one deployed long-term on the mainnet. Someone just needs to put in the time.

**Comment by vieyang** [comment]
wooo, Waiting for atomic swap of eth.

**Comment by vieyang** [comment]
> It should be noted Bitcoin usually has a major problem with transaction IDs.

so, as ethereum, if we don't use a smart contract, there still has a problem with ethereum transaction IDs?

**Comment by kayabaNerve** [comment]
I don't believe Ethereum has a similar problem, but I haven't looked into the specifics. That said, even if it does, it can still be used on both sides. The reason BTC TX malleability is a problem is because they contain the scripts. Since Ethereum uses an account model, and a SC is used for the scripting, it's not relevant.

**Comment by vieyang** [comment]
I still have a hard time understanding the problem with Bitcoin transactions, I will try to figure it out.

**Comment by kayabaNerve** [comment]
It has no effect on Ethereum, to be clear.

That said, here's the short version:
- Every BTC output is locked with a script.
- You can spend the output by getting it to resolve to true.
- Your input contains arguments to get the script to equal true.
- One argument is the signature.
- Because BTC Script uses a stack system, and only the top-most element needs to equal true, you can put any other arguments you want in ([signature] and [x, y, z, signature] when passed to a signature check will both pop the signature AND push true).
- x, y, z are junk, and not used to create the signature. That said, they're still part of the transaction hash.
- You need to know every TX hash in the swap in advance for BTC. BTC allows TX hashes to be changed by anyone. You therefore need SegWit, which forbids junk arguments (and similar attacks).

Ethereum isn't affected because you don't need to know every Ethereum TX hash in advance. The account model, instead of UTXO model, removes that requirement.

**Comment by kayabaNerve** [comment]
https://en.bitcoin.it/wiki/Transaction_malleability is the post on the BTC wiki about it. That warning is meant to state LTC-XMR is possible, yet BCH-XMR isn't.

On a side note, BTC-BCH and LTC-BCH is possible (where BCH takes the place of XMR), but it's inefficient compared to the existing atomic swap protocol and not beneficial. Just a fun fact.

**Comment by vieyang** [comment]
ok, thank you for your help.
